# Generated by Django 6.1 on 2026-08-31 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دک')),
                ('icon', models.CharField(default='fa-layer-group', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='#7C3AED', max_length=20, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دک',
                'verbose_name_plural': 'دک\u200cها',
                'db_table': 'flashcard_decks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=500, verbose_name='سمت اول')),
                ('back', models.CharField(max_length=500, verbose_name='سمت دوم')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='راهنما')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='ضریب آسانی')),
                ('interval', models.IntegerField(default=0, verbose_name='فاصله (روز)')),
                ('repetitions', models.IntegerField(default=0, verbose_name='تکرار')),
                ('status', models.CharField(choices=[('new', 'تازه'), ('learning', 'در حال یادگیری'), ('mastered', 'مسلط'), ('expert', 'حرفه\u200cای')], default='new', max_length=20, verbose_name='وضعیت')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مرور')),
                ('next_review', models.DateField(blank=True, null=True, verbose_name='مرور بعدی')),
                ('correct_count', models.IntegerField(default=0, verbose_name='تعداد صحیح')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='تعداد اشتباه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.deck')),
            ],
            options={
                'verbose_name': 'کارت',
                'verbose_name_plural': 'کارت\u200cها',
                'db_table': 'flashcard_cards',
                'ordering': ['next_review', '-created_at'],
            },
        ),
    ]
