# Generated by Django 6.1 on 2026-09-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.CharField(max_length=500, verbose_name='سمت دوم (فارسی)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(max_length=500, verbose_name='سمت اول (کرهای)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='repetitions',
            field=models.IntegerField(default=0, verbose_name='تعداد تکرار'),
        ),
    ]
