# Generated by Django 6.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اتاق')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('level', models.CharField(choices=[('A1', 'A1 - مبتدی کامل'), ('A2', 'A2 - مبتدی'), ('B1', 'B1 - متوسط'), ('B2', 'B2 - متوسط بالا'), ('C1', 'C1 - پیشرفته'), ('C2', 'C2 - حرفه\u200cای')], default='A1', max_length=2, verbose_name='سطح')),
                ('status', models.CharField(choices=[('active', '🟢 فعال'), ('full', '🔴 پر'), ('inactive', '⚪ غیرفعال')], default='active', max_length=10, verbose_name='وضعیت')),
                ('max_members', models.PositiveIntegerField(default=50, verbose_name='حداکثر اعضا')),
                ('current_members', models.PositiveIntegerField(default=0, verbose_name='اعضای فعلی')),
                ('daily_mission', models.TextField(blank=True, verbose_name='ماموریت روزانه')),
                ('mission_progress', models.JSONField(blank=True, default=dict, verbose_name='پیشرفت ماموریت')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='کل XP')),
                ('weekly_xp_goal', models.PositiveIntegerField(default=10000, verbose_name='هدف هفتگی XP')),
                ('weekly_xp_current', models.PositiveIntegerField(default=0, verbose_name='XP فعلی هفته')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'متن'), ('system', 'سیستم'), ('announcement', 'اعلان')], default='text', max_length=20)),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='پین شده')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='studyroom.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'اسپم'), ('harassment', 'آزار'), ('inappropriate', 'محتوای نامناسب'), ('other', 'سایر')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('resolved', 'رسیدگی شده'), ('dismissed', 'رد شده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='studyroom.roommessage')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='studyroom.room')),
            ],
            options={
                'db_table': 'room_reports',
            },
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='studyroom.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_blocks',
                'unique_together': {('user', 'blocked_user', 'room')},
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '👑 Leader'), ('moderator', '🛡️ Moderator'), ('mentor', '📚 Mentor'), ('member', '👤 Member')], default='member', max_length=10, verbose_name='نقش')),
                ('status', models.CharField(choices=[('offline', '⚪ آفلاین'), ('studying', '🟢 در حال مطالعه'), ('idle', '🟡 غیرفعال')], default='offline', max_length=10, verbose_name='وضعیت')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='XP')),
                ('weekly_xp', models.PositiveIntegerField(default=0, verbose_name='XP هفته')),
                ('study_time_today', models.PositiveIntegerField(default=0, verbose_name='زمان مطالعه امروز (دقیقه)')),
                ('study_streak', models.PositiveIntegerField(default=0, verbose_name='روزهای پیاپی')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='آخرین مطالعه')),
                ('is_studying', models.BooleanField(default=False, verbose_name='در حال مطالعه')),
                ('study_start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع مطالعه')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='studyroom.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_members',
                'ordering': ['-xp'],
                'unique_together': {('user', 'room')},
            },
        ),
        migrations.CreateModel(
            name='RoomMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes_made', to=settings.AUTH_USER_MODEL)),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes_received', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='studyroom.room')),
            ],
            options={
                'db_table': 'room_mutes',
                'unique_together': {('muted_user', 'room')},
            },
        ),
    ]
