# Generated by Django 6.1 on 2026-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='weekly_challenge_badge',
            field=models.CharField(blank=True, default='🏆', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='weekly_challenge_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='weekly_challenge_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='weekly_challenge_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommember',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roommember',
            name='weekly_challenge_contribution',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
